# -*- coding: utf-8 -*-
"""Deployment Padi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-f_W5K_pjf3bMvH2FVWc9_WtRPSY-Uqn
"""

import streamlit as st
import pandas as pd
import numpy as np
import pickle

# 1. Load model dan urutan fitur kolom dari file pkl
try:
    with open('model_padi.pkl', 'rb') as file:
        model = pickle.load(file)

    with open('fitur_kolom.pkl', 'rb') as file:
        fitur_kolom = pickle.load(file)
except FileNotFoundError:
    st.error("Error: File 'model_padi.pkl' atau 'fitur_kolom.pkl' tidak ditemukan di folder GitHub kamu!")

# 2. Membuat Tampilan Aplikasi Web
st.set_page_config(page_title="Prediksi Padi Sumatera", page_icon="🌾")
st.title("🌾 Aplikasi Estimasi Produksi Padi Sumatera")
st.write("Masukkan indikator di bawah ini untuk memprediksi jumlah produksi padi (Ton):")

st.markdown("---")

# Form Input dari Pengguna
tahun = st.number_input("📅 Tahun", min_value=1990, max_value=2030, value=2026, step=1)
luas_panen = st.number_input("📐 Luas Panen (Ha)", min_value=0.0, value=100000.0, step=500.0)
curah_hujan = st.number_input("🌧️ Curah Hujan (mm)", min_value=0.0, value=1500.0, step=10.0)
kelembapan = st.number_input("💧 Kelembapan (%)", min_value=0.0, max_value=100.0, value=80.0, step=0.5)
suhu = st.number_input("🌡️ Suhu Rata-rata (°C)", min_value=0.0, max_value=50.0, value=26.0, step=0.1)

st.markdown("---")

# 3. Tombol Eksekusi Prediksi
if st.button("🔮 Hitung Prediksi Produksi"):

    # Memasukkan nilai sesuai urutan input ke dalam list
    input_values = [tahun, luas_panen, curah_hujan, kelembapan, suhu]

    # SOLUSI AMAN: Membuat DataFrame langsung menggunakan struktur kolom asli (fitur_kolom)
    # Ini akan mencegah error KeyError akibat perbedaan huruf kapital/spasi
    df_input = pd.DataFrame([input_values], columns=fitur_kolom)

    try:
        # Lakukan prediksi
        hasil_prediksi = model.predict(df_input)

        # Tampilkan hasil ke layar web
        st.success(f"### Estimasi Produksi Padi: **{hasil_prediksi[0]:,.2f} Ton**")

    except Exception as e:
        st.error(f"Terjadi kesalahan saat pemrosesan model: {e}")